{% set name = "anchor-droplet-chip" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7a81eeb472e2bd90dbca39ce45efc5981adf81f2e22aea9d068a85115e38748

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.9.0
    - setuptools-scm
    - wheel
  run:
    - dask-core
    - fire
    - jupyterlab
    - magicgui
    - matplotlib-base
    - napari
    - nd2
    - numpy
    - pandas
    # - pytest-qt
    - python >={{ python_min }}
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tifffile
    - tqdm
    - zarr-tools
    - zenodo_get

test:
  imports:
    - adc
    - imreg_dft
  commands:
    - pip list
    # - pip check  # Fails due to pyqt6
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/anchor-droplet-chip
  summary: Segment organoids and measure intensities
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BaroudLab/anchor-droplet-chip

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
